#ifndef VGA_H
#define VGA_H

// VGA memory constants
char * VGA_MODE_PTR = (char *)0xA0000; // VGA mem begins here.

// VGA regs constants
#define VGA_MODE_CONTROL 0x3C0
#define VGA_OVERSCAN 0x3C0
#define VGA_ENABLE_COLOR_PLANE 0x3C0
#define VGA_HORIZONTAL_PANNING 0x3C0
#define VGA_COLOR_SELECT 0x3C0
#define VGA_MISC_OUTPUT 0x3C2
#define VGA_CLOCK_MODE 0x3C4
#define VGA_CHAR_SELECT 0x3C4
#define VGA_MEM_MODE 0x3C4
#define VGA_MODE 0x3CE
#define VGA_MISC 0x3CE
#define VGA_HORIZONTAL_TOTAL 0x3D4
#define VGA_END_HORIZONTAL_DISPLAY 0x3D4
#define VGA_START_HORIZONTAL_BLANK 0x3D4
#define VGA_END_HORIZONTAL_BLANK 0x3D4
#define VGA_START_HORIZONTAL_RETRACE 0x3D4
#define VGA_END_HORIZONTAL_RETRACE 0x3D4
#define VGA_VERTICAL_TOTAL 0x3D4
#define VGA_OVERFLOW 0x3D4
#define VGA_PRESET_ROW_SCAN 0x3D4
#define VGA_MAX_SCAN_LINE 0x3D4
#define VGA_START_VERTICAL_RETRACE 0x3D4
#define VGA_END_VERTICAL_RETRACE 0x3D4
#define VGA_END_ENABLE_DISPLAY 0x3D4
#define VGA_LOGICAL_WIDTH 0x3D4
#define VGA_UNDERLINE_LOCATION 0x3D4
#define VGA_START_VERTICAL_BLANKING 0x3D4
#define VGA_END_VERTICAL_BLANKING 0x3D4
#define VGA_MODE_CONTROL_2 0x3D4

// Mode 12h Register Values (640x480, 16-color planar mode)
unsigned char mode_12h_regs[] = {
    0x01,  // VGA_MODE_CONTROL
    0x00,  // VGA_OVERSCAN
    0x0F,  // VGA_ENABLE_COLOR_PLANE
    0x00,  // VGA_HORIZONTAL_PANNING
    0x00,  // VGA_COLOR_SELECT
    0xE3,  // VGA_MISC_OUTPUT
    0x01,  // VGA_CLOCK_MODE
    0x00,  // VGA_CHAR_SELECT
    0x02,  // VGA_MEM_MODE
    0x00,  // VGA_MODE
    0x05,  // VGA_MISC
    0x5F,  // VGA_HORIZONTAL_TOTAL
    0x4F,  // VGA_END_HORIZONTAL_DISPLAY
    0x50,  // VGA_START_HORIZONTAL_BLANK
    0x82,  // VGA_END_HORIZONTAL_BLANK
    0x54,  // VGA_START_HORIZONTAL_RETRACE
    0x80,  // VGA_END_HORIZONTAL_RETRACE
    0x0B,  // VGA_VERTICAL_TOTAL
    0x3E,  // VGA_OVERFLOW
    0x00,  // VGA_PRESET_ROW_SCAN
    0x40,  // VGA_MAX_SCAN_LINE
    0xEA,  // VGA_START_VERTICAL_RETRACE
    0x8C,  // VGA_END_VERTICAL_RETRACE
    0xDF,  // VGA_END_ENABLE_DISPLAY
    0x28,  // VGA_LOGICAL_WIDTH
    0x00,  // VGA_UNDERLINE_LOCATION
    0xE7,  // VGA_START_VERTICAL_BLANKING
    0x04,  // VGA_END_VERTICAL_BLANKING
    0xE3   // VGA_MODE_CONTROL_2
};

// VGA functions
void init_vga_12h_mode(void);
void clear_screen_vga(void);
void putpixel(int x, int y, unsigned char color);

#endif // VGA_H
